package entity.po;
// default package
// Generated 2017-4-6 20:52:26 by Hibernate Tools 4.3.1

/**
 * Org generated by hbm2java
 */
public class Org implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int orgid;
	private Integer parentorgid;
	private Integer level;
	private String orgname;
	private String manager;
	private String linkman;
	private String linktel;

	public Org() {
	}

	public Org(int orgid) {
		this.orgid = orgid;
	}

	public Org(int orgid, Integer parentorgid, Integer level, String orgname,
			String manager, String linkman, String linktel) {
		this.orgid = orgid;
		this.parentorgid = parentorgid;
		this.level = level;
		this.orgname = orgname;
		this.manager = manager;
		this.linkman = linkman;
		this.linktel = linktel;
	}

	public int getOrgid() {
		return this.orgid;
	}

	public void setOrgid(int orgid) {
		this.orgid = orgid;
	}

	public Integer getParentorgid() {
		return this.parentorgid;
	}

	public void setParentorgid(Integer parentorgid) {
		this.parentorgid = parentorgid;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinktel() {
		return this.linktel;
	}

	public void setLinktel(String linktel) {
		this.linktel = linktel;
	}

}
