select aa.*, bb.posiname from
(select 
emp.empid        as     empid         ,
emp.empcode      as     empcode       ,
emp.operatorid   as     operatorid    ,
emp.userid       as     userid        ,
emp.empname      as     empname       ,
emp.realname     as     realname      ,
emp.gender       as     gender        ,
emp.birthdate    as     birthdate     ,
emp.position     as     position      ,
emp.empstatus    as     empstatus     ,
emp.cardtype     as     cardtype      ,
emp.cardno       as     cardno        ,
emp.indate       as     indate        ,
emp.outdate      as     outdate       ,
emp.otel         as     otel          ,
emp.oaddress     as     oaddress      ,
emp.ozipcode     as     ozipcode      ,
emp.oemail       as     oemail        ,
emp.faxno        as     faxno         ,
emp.mobileno     as     mobileno      ,
emp.qq           as     qq            ,
emp.htel         as     htel          ,
emp.haddress     as     haddress      ,
emp.hzipcode     as     hzipcode      ,
emp.pemail       as     pemail        ,
emp.party        as     party         ,
emp.degree       as     degree        ,
emp.sortno       as     sortno        ,
emp.major        as     major         ,
emp.specialty    as     specialty     ,
emp.workexp      as     workexp       ,
emp.regdate      as     regdate       ,
emp.createtime   as     createtime    ,
emp.lastmodytime as     lastmodytime  ,
emp.orgidlist    as     orgidlist     ,
emp.remark       as     remark        ,
emp.tenant_id    as     tenant_id     ,
emp.app_id       as     app_id        ,
emp.weibo        as     weibo         ,
               
emppos.empnamesy     as     empnamesy         ,            
emppos.orgid     as     orgid         ,  
emppos.posid     as     posid         ,  
emppos.isleader  as     isleader      ,  
emppos.issync    as     issync        ,  
emppos.ismain    as     ismain          

from org_sfy_emppos emppos inner join org_employee emp
on emppos.empid = emp.empid) aa  left join org_position bb
on aa.posid = bb.positionid