package entity;
// default package
// Generated 2017-4-6 20:57:37 by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userid;
	private String name;

	public User() {
	}

	public User(String userid) {
		this.userid = userid;
	}

	public User(String userid, String name) {
		this.userid = userid;
		this.name = name;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
